apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: makafuiatimpo/udagram-api-feed:v1
        env:
        - name: POSTGRES_USERNAME
          value: <>
        - name: POSTGRES_PASSWORD
          value: <>
        - name: POSTGRES_DB
          value: <>
        - name: POSTGRES_HOST
          value: <>
        - name: AWS_REGION
          value: <>
        - name: AWS_BUCKET
          value: <>
        - name: AWS_ACCESS_KEY_ID
          value: <>
        - name: AWS_SECRET_KEY
          value: <>
        - name: URL
          value: <>
        - name: JWT_SECRET
          value: <>
        ports:
        - containerPort: 8080